### ISSUE TITLE
How come this plays wav file when pyaudio couldn't?

### ISSUE THREAD

**Issue by talksik** [larsimmisch/pyalsaaudio#127]
Hey there, I have been trying to diagnose an issue with pyaudio.

When trying to play back a wav file from online that has a sampling rate of 22050, it gives me an error "invalid sample rate". This is with a raspberry pi zero that has a mic/amp setup. This is with pyaudio. Pyaudio does play files that are 48kHz sampling rate likely because the output device has that rate as a default so it has no issues.

Now, the same audio file played with `aplay x.wav` works. 

Also, the same file with this library (pyalsaaudio) works. 

Is this because alsa resamples under the hood and converts to the correct rate? Doesn't pyaudio use alsa under the hood, and so why wouldn't it work with pyaudio?

Thank you!

**Comment by larsimmisch** [comment]
I'm sure that alsaaudio does not resample under the hood, and portaudio is on top of alsaaudio AFAIK, so this is indeed mystifying. Are you maybe opening a different device on alsaaudio vs. on portaudio?

I'll close this issue, because it's not really a pyalsaaudio issue. Feel free to comment anyway.
